#!/usr/bin/env python3
import os
import socket
from multiprocessing import Process

TAM_MSG = 1024         # Tamanho do bloco de mensagem
HOST = '0.0.0.0'       # IP de alguma interface do Servidor
PORT = 40000           # Porta que o Servidor escuta

def processa_msg_cliente(msg, con, cliente):
    msg = msg.decode().strip()
    print('Cliente', cliente, 'enviou:', msg)
    msg = msg.split()
    comando = msg[0].upper()

    if comando == 'GET':
        nome_arq = " ".join(msg[1:])
        print('Arquivo solicitado:', nome_arq)
        try:
            status_arq = os.stat(nome_arq)
            con.send(str.encode(f'+OK {status_arq.st_size}\n'))
            with open(nome_arq, "rb") as arq:
                while True:
                    dados = arq.read(TAM_MSG)
                    if not dados:
                        break
                    con.send(dados)
        except Exception as e:
            con.send(str.encode(f'-ERR {e}\n'))

    elif comando == 'LIST':
        lista_arq = os.listdir('.')
        con.send(str.encode(f'+OK {len(lista_arq)}\n'))
        for nome_arq in lista_arq:
            if os.path.isfile(nome_arq):
                status_arq = os.stat(nome_arq)
                con.send(str.encode(f'arq: {nome_arq} - {status_arq.st_size / 1024:.1f}KB\n'))
            elif os.path.isdir(nome_arq):
                con.send(str.encode(f'dir: {nome_arq}\n'))
            else:
                con.send(str.encode(f'esp: {nome_arq}\n'))

    elif comando == 'CWD':
        if len(msg) < 2:
            con.send(str.encode('-ERR Missing directory\n'))
        else:
            novo_diretorio = " ".join(msg[1:])
            try:
                os.chdir(novo_diretorio)
                con.send(str.encode(f'+OK Changed directory to {novo_diretorio}\n'))
            except FileNotFoundError:
                con.send(str.encode(f'-ERR Directory not found: {novo_diretorio}\n'))
            except Exception as e:
                con.send(str.encode(f'-ERR {e}\n'))

    elif comando == 'QUIT':
        con.send(str.encode('+OK\n'))
        return False

    else:
        con.send(str.encode('-ERR Invalid command\n'))

    return True

def processa_cliente(con, cliente):
    print('Cliente conectado:', cliente)
    while True:
        try:
            msg = con.recv(TAM_MSG)
            if not msg or not processa_msg_cliente(msg, con, cliente):
                break
        except Exception as e:
            print(f'Erro com o cliente {cliente}: {e}')
            break
    con.close()
    print('Cliente desconectado:', cliente)

def main():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    serv = (HOST, PORT)
    sock.bind(serv)
    sock.listen(50)
    print(f"Servidor escutando em {HOST}:{PORT}")

    while True:
        try:
            con, cliente = sock.accept()
            print(f"Nova conexão: {cliente}")
            # Cria um processo para atender o cliente
            p = Process(target=processa_cliente, args=(con, cliente))
            p.start()
        except KeyboardInterrupt:
            print("\nServidor encerrado.")
            break
        except Exception as e:
            print(f"Erro no servidor: {e}")
            break

    sock.close()

if __name__ == '__main__':
    main()
